{% set name = "langchain-core" %}
{% set version = "0.3.58" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/langchain-ai/langchain/archive/refs/tags/{{ name }}=={{ version }}.tar.gz
  sha256: 13e57e87ff86649e36373907630947e79e20ae9b7cf610517ff0d3b32120c043

build:
  number: 0
  script: {{ PYTHON }} -m pip install ./libs/core --no-deps --no-build-isolation -vv
  skip: True  # [py<39]

requirements:
  host:
    - python
    - pip
    - pdm-backend
  run:
    - python
    - langsmith >=0.1.125,<0.4
    - tenacity >=8.1.0,<10.0.0,!=8.4.0
    - jsonpatch >=1.33,<2.0
    - pyyaml >=5.3
    - packaging >=23.2,<25
    - typing-extensions >=4.7
    - pydantic >=2.5.2,<3  # [py<=312]
    - pydantic >=2.7.4,<3  # [py>=313]

test:
  imports:
    - langchain_core
  requires:
    - pip
  commands:
    - pip check
    # Missing dependency `blockbuster` for conftest.py (can't run any tests without it)

about:
  home: https://github.com/langchain-ai/langchain
  summary: Core APIs for LangChain, the LLM framework for buildilng applications through composability
  description: LangChain Core contains the core abstractions powering LangChain, including LangChain Expression Language.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  dev_url: https://github.com/langchain-ai/langchain/tree/master/libs/core
  doc_url: https://api.python.langchain.com/en/stable/core_api_reference.html

extra:
  anaconda-services:
    recipe-maintainers:
       - bkreider
    comment: "Dependency for deepeval requested from https://anaconda.zendesk.com/agent/tickets/53943"

  recipe-maintainers:
    - hinthornw
    - baskaryan
    - hwchase17
    - efriis
    - agola11
    - pavelzw
